services:
  backend:
    build:
      context: ./backend
    container_name: recruitment-backend
    environment:
      - NODE_ENV=production
      - PORT=3101
    ports:
      - "3101:3101"

  frontend:
    build:
      context: ./frontend
    container_name: recruitment-frontend
    depends_on:
      - backend
    ports:
      - "3100:80"
